# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-17 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='reply',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Отет администратора'),
        ),
    ]
