# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-17 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_subscriber_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='last_name',
        ),
    ]
