# Generated by Django 2.0.3 on 2018-03-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(help_text='Пожалуйста, введите ваше имя...', max_length=50, verbose_name='Имя')),
                ('question_theme', models.CharField(help_text='Пожалуйста, введите тему вопроса...', max_length=50, verbose_name='Тема вопроса')),
                ('question', models.TextField(help_text='Задайте Ваш вопрос...', verbose_name='Ваш вопрос')),
                ('reply', models.TextField(blank=True, null=True, verbose_name='Ответ администратора')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('replied', models.BooleanField(default=False, verbose_name='Отвечено')),
            ],
            options={
                'verbose_name': 'Вопрос поситителей',
                'verbose_name_plural': 'Вопросы поситителей',
            },
        ),
    ]
