# Generated by Django 2.0.3 on 2018-03-29 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='question',
            new_name='info',
        ),
    ]
