# Generated by Django 2.0.3 on 2018-03-29 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, db_index=True, default=None, max_length=64, verbose_name='Категория')),
                ('category_slug', models.SlugField(max_length=200, unique=True)),
                ('category_description', models.TextField(blank=True, default=None, verbose_name='Опиание котегории')),
                ('category_is_active', models.BooleanField(default=True, verbose_name='Активная')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Category_photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_photo', models.ImageField(upload_to='products/product_category_photos/', verbose_name='Фотограифя')),
                ('category_photo_is_active', models.BooleanField(default=True, verbose_name='Активная')),
                ('category_photo_is_main', models.BooleanField(default=False, verbose_name='Главная (превью)')),
                ('category_photo_created', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('category_photo_updated', models.DateTimeField(auto_now=True, verbose_name='Изменена')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Фотография категории',
                'verbose_name_plural': 'Фотографии категорий',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, db_index=True, default=None, max_length=200, verbose_name='Наименование')),
                ('product_slug', models.SlugField(max_length=200)),
                ('product_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('product_description', models.TextField(blank=True, default=None, verbose_name='Описание')),
                ('product_stock', models.PositiveIntegerField(verbose_name='На складе')),
                ('product_is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('product_created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('product_updated', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('product_category', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='products.Category', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='Product_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_user_name', models.CharField(help_text='Пожалуйста, введите ваше имя...', max_length=50, verbose_name='Имя')),
                ('pc_comment', models.TextField(help_text='Задайте Ваш вопрос...', verbose_name='Ваш вопрос')),
                ('pc_reply', models.TextField(blank=True, null=True, verbose_name='Ответ администратора')),
                ('pc_replied', models.BooleanField(default=False, verbose_name='Отвечено')),
                ('pc_created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('pc_updated', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('pc_product', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Комметарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Product_photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_photo', models.ImageField(upload_to='products/products_images/', verbose_name='Фотограифя')),
                ('product_photo_is_active', models.BooleanField(default=True, verbose_name='Активная')),
                ('product_photo_is_main', models.BooleanField(default=False, verbose_name='Главная (превью)')),
                ('product_photo_created', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('product_photo_updated', models.DateTimeField(auto_now=True, verbose_name='Изменена')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фотография продукта',
                'verbose_name_plural': 'Фотографии продуктов',
            },
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id', 'product_slug')},
        ),
    ]
