# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-17 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_photo',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Category_photo',
        ),
    ]
